name: DevOps Assembly Line

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  Infrastructure-Provisioning:
    name: Infrastructure Provisioning
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo using Terraform to create AWS infra

  configuration-management-development:
    name: CM / development
    environment: development
    runs-on: ubuntu-latest
    needs: Infrastructure-Provisioning
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo using Ansible for config mgmt
  configuration-management-test:
    name: CM / test
    environment: test
    runs-on: ubuntu-latest
    needs: Infrastructure-Provisioning
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo using Ansible for config mgmt
  configuration-management-user_acceptance_testing:
    name: CM / user_acceptance_testing
    environment: user_acceptance_testing
    runs-on: ubuntu-latest
    needs: Infrastructure-Provisioning
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo using Ansible for config mgmt
  configuration-management-production:
    name: CM / production
    environment: production
    runs-on: ubuntu-latest
    needs: Infrastructure-Provisioning
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo using Ansible for config mgmt
  
  build-development:
      name: Build / development
      environment: development
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: Run a one-line script
          run: echo using Ansible for config mgmt
  deploy-development:
      name: Deploy / development
      environment: development
      runs-on: ubuntu-latest
      needs: [build-development, configuration-management-development]
      steps:
        - uses: actions/checkout@v3

        - name: Run a one-line script
          run: echo using Ansible for config mgmt
  build-test:
    name: Build / test
    environment: test
    runs-on: ubuntu-latest
    needs: [deploy-development]
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo using Ansible for config mgmt
        
  deploy-test:
      name: Deploy / test
      environment: test
      runs-on: ubuntu-latest
      needs: [configuration-management-test,build-test]
      steps:
        - uses: actions/checkout@v3

        - name: Run a one-line script
          run: echo using Ansible for config mgmt
  
  build-user_acceptance_testing:
    name: Build / user_acceptance_testing
    environment: user_acceptance_testing
    runs-on: ubuntu-latest
    needs: [deploy-test]
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo using Ansible for config mgmt
  
  deploy-user_acceptance_testing:
      name: Deploy / user_acceptance_testing
      environment: user_acceptance_testing
      runs-on: ubuntu-latest
      needs: [configuration-management-user_acceptance_testing,build-user_acceptance_testing]
      steps:
        - uses: actions/checkout@v3

        - name: Run a one-line script
          run: echo using Ansible for config mgmt
  
  
  build-production:
    name: Build / production
    environment: production
    runs-on: ubuntu-latest
    needs: [deploy-user_acceptance_testing]
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo using Ansible for config mgmt
  
  deploy-production:
      name: Deploy / production
      environment: production
      runs-on: ubuntu-latest
      needs: [configuration-management-production,build-production]
      steps:
        - uses: actions/checkout@v3

        - name: Run a one-line script
          run: echo using Ansible for config mgmt
  
    