name: DevOps Assembly Line

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  Infrastructure-Provisioning:
    name: Infrastructure Provisioning
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo using Terraform to create AWS infra

  configuration-management-development:
    name: Configuration Management
    environment: development
    runs-on: ubuntu-latest
    needs: Infrastructure-Provisioning
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo using Ansible for config mgmt
  configuration-management-test:
    name: Configuration Management
    environment: test
    runs-on: ubuntu-latest
    needs: Infrastructure-Provisioning
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo using Ansible for config mgmt
  configuration-management-user_acceptance_testing:
    name: Configuration Management
    environment: user_acceptance_testing
    runs-on: ubuntu-latest
    needs: Infrastructure-Provisioning
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo using Ansible for config mgmt
  configuration-management-production:
    name: Configuration Management
    environment: production
    runs-on: ubuntu-latest
    needs: Infrastructure-Provisioning
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo using Ansible for config mgmt
  

  