name: matrix-workflow
on: 
  workflow_dispatch:
permissions:
  contents: read
jobs:
  infrastructure_provisioning:
    strategy:
      matrix:
        env: [test,dev]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo ${{ matrix.env }}
