name: matrix-workflow
on: 
  workflow_dispatch:
permissions:
  contents: read
jobs:
  infrastructure_provisioning:
    strategy:
      matrix:
        env: [dev,test,uat,prod]
    runs-on: ubuntu-latest
    # name: Provisioning ${{ matrix.env }}
    name: Infrastructure Provisioning
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo ${{ matrix.env }}
