on: 
  workflow_call: 
jobs:
  reusing_workflow:
    name: reusing_workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo using Terraform to create AWS infra